
set(WATCOM TRUE)
set(OLD_WATCOM TRUE)

set(CMAKE_CROSSCOMPILING FALSE)

add_definitions(-dWATCOM -dOLD_WATCOM)

get_filename_component(here "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(watcom "${here}" PATH)
get_filename_component(watcom "${watcom}" PATH)
get_filename_component(watcom "${watcom}" PATH)
set(watcom "${watcom}/_tools/watcom10")
set(wlib "${here}/wlib.cmd")
set(wlink "${here}/wlink.cmd")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i386)

set(CMAKE_C_COMPILER "${here}/wcc386.cmd")
set(CMAKE_CXX_COMPILER "${here}/wcc386.cmd")
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_C_ABI_COMPILED TRUE)
set(CMAKE_CXX_ABI_COMPILED TRUE)
set(CMAKE_C_COMPILER_ID WATCOM10)
set(CMAKE_CXX_COMPILER_ID WATCOM10)
set(CMAKE_C_COMPILER_VERSION "10.0a")
set(CMAKE_CXX_COMPILER_VERSION "10.0a")
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)

set(CMAKE_FIND_ROOT_PATH "${watcom}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "-i`${watcom}/h -i`${watcom}/h/nt -bt`nt -fpi87 -fp5 -j -mf -zq -d+")
set(CMAKE_C_FLAGS_DEBUG_INIT "-db -d3 -5s -od")
set(CMAKE_C_FLAGS_RELEASE_INIT "-dNDEBUG -5r -s -oamilernt -s")
set(CMAKE_CXX_FLAGS_INIT "-i`${watcom}/h -i`${watcom}/h/nt -bt`nt -fpi87 -fp5 -j -mf -zq -d+")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-db -d3 -5s -od")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-dNDEBUG -5r -s -oamilernt -s")

set(CMAKE_EXE_LINKER_FLAGS_INIT " option quiet option caseexact ")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " debug all ")
set(CMAKE_EXE_LINKER_FLAGS_DELWITHDEBINFO_INIT " debug all ")

set(CMAKE_LIBRARY_PATH_FLAG "libpath ")
set(CMAKE_LINK_LIBRARY_FLAG "library ")
set(CMAKE_LINK_LIBRARY_FILE_FLAG "library ")
set(CMAKE_LINK_OBJECT_FILE_FLAG "file ")

set(CMAKE_CREATE_WIN32_EXE "system nt_win")
set(CMAKE_C_CREATE_WIN32_EXE "system nt_win")
set(CMAKE_CREATE_CONSOLE_EXE "system nt")
set(CMAKE_C_CREATE_CONSOLE_EXE "system nt")

set(CMAKE_FIND_LIBRARY_SUFFIXES ".lib")

set(CMAKE_MANGLE_OBJECT_FILE_NAMES "ON")

set(CMAKE_C_USE_RESPONSE_FILE_FOR_INCLUDES 0)
set(CMAKE_CXX_USE_RESPONSE_FILE_FOR_INCLUDES 0)

foreach(type CREATE_SHARED_LIBRARY CREATE_SHARED_MODULE LINK_EXECUTABLE)
    set(CMAKE_C_${type}_USE_WATCOM_QUOTE 1)
    set(CMAKE_CXX_${type}_USE_WATCOM_QUOTE 1)
endforeach()

set(CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> -d_WIN32 <DEFINES> <INCLUDES> <FLAGS> -fo`<OBJECT> <SOURCE>")
set(CMAKE_CXX_COMPILE_OBJECT "<CMAKE_CXX_COMPILER> -d_WIN32 <DEFINES> <INCLUDES> <FLAGS> -fo`<OBJECT> <SOURCE>")

set(CMAKE_C_LINK_EXECUTABLE "${wlink} name <TARGET> <LINK_FLAGS> file {<OBJECTS>} <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "${wlink} name <TARGET> <LINK_FLAGS> file {<OBJECTS>} <LINK_LIBRARIES>")

set(CMAKE_C_CREATE_STATIC_LIBRARY "${wlib} -q -c -n -b <TARGET_QUOTED> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "${wlib} -q -c -n -b <TARGET_QUOTED> <LINK_FLAGS> <OBJECTS>")

set(CMAKE_C_CREATE_IMPORT_LIBRARY "${wlib} -c -q -n -b <TARGET_IMPLIB> +<TARGET_QUOTED>")
set(CMAKE_CXX_CREATE_IMPORT_LIBRARY "${wlib} -c -q -n -b <TARGET_IMPLIB> +<TARGET_QUOTED>")
